// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxflswukbamquskdipzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Zmxzd3VrYmFtcXVza2RpcHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjE4OTksImV4cCI6MjA3MTg5Nzg5OX0.tgftSesQ8B6eFvsMdX885y9gE2u3XrQu5k3jWEpWA4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});